/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.51
 * Generated at: 2018-08-28 07:44:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class air_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"59931\",secure:\"59937\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("<body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-2\" data-genuitec-path=\"/proto/WebContent/air.jsp\">\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/air?cmd=air_view\" method=\"POST\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-2\" data-genuitec-path=\"/proto/WebContent/air.jsp\">\r\n");
      out.write("항공사\r\n");
      out.write("<select name=\"airline\">\r\n");
      out.write("\t<option><항공사를 선택해주세요></option>\r\n");
      out.write("\t<option value=\"AAR\">아시아나</option>\r\n");
      out.write("\t<option value=\"ABL\">에어부산</option>\r\n");
      out.write("\t<option value=\"ESR\">이스타</option>\r\n");
      out.write("\t<option value=\"JJA\">제주항공</option>\r\n");
      out.write("\t<option value=\"JNA\">진에어</option>\r\n");
      out.write("\t<option value=\"KAL\">대한항공</option>\r\n");
      out.write("\t<option value=\"TWB\">티웨이항공</option>\r\n");
      out.write("</select>\r\n");
      out.write("출발공항\r\n");
      out.write("<select name=\"depairport\">\r\n");
      out.write("\t<option><공항을 선택해주세요></option>\r\n");
      out.write("\t<option value=\"NAARKJB\">무안</option>\r\n");
      out.write("\t<option value=\"NAARKJJ\">광주</option>\r\n");
      out.write("\t<option value=\"NAARKJK\">군산</option>\r\n");
      out.write("\t<option value=\"NAARKJY\">여수</option>\r\n");
      out.write("\t<option value=\"NAARKNW\">원주</option>\r\n");
      out.write("\t<option value=\"NAARKNY\">양양</option>\r\n");
      out.write("\t<option value=\"NAARKPC\">제주</option>\r\n");
      out.write("\t<option value=\"NAARKPK\">김해</option>\r\n");
      out.write("\t<option value=\"NAARKPS\">사천</option>\r\n");
      out.write("\t<option value=\"NAARKPU\">울산</option>\r\n");
      out.write("\t<option value=\"NAARKSI\">인천</option>\r\n");
      out.write("\t<option value=\"NAARKSS\">김포</option>\r\n");
      out.write("\t<option value=\"NAARKTH\">포항</option>\r\n");
      out.write("\t<option value=\"NAARKTN\">대구</option>\r\n");
      out.write("\t<option value=\"NAARKTU\">청주</option>\r\n");
      out.write("</select>\r\n");
      out.write("도착공항\r\n");
      out.write("<select name=\"arrairport\">\r\n");
      out.write("\t<option><공항을 선택해주세요></option>\r\n");
      out.write("\t<option value=\"NAARKJB\">무안</option>\r\n");
      out.write("\t<option value=\"NAARKJJ\">광주</option>\r\n");
      out.write("\t<option value=\"NAARKJK\">군산</option>\r\n");
      out.write("\t<option value=\"NAARKJY\">여수</option>\r\n");
      out.write("\t<option value=\"NAARKNW\">원주</option>\r\n");
      out.write("\t<option value=\"NAARKNY\">양양</option>\r\n");
      out.write("\t<option value=\"NAARKPC\">제주</option>\r\n");
      out.write("\t<option value=\"NAARKPK\">김해</option>\r\n");
      out.write("\t<option value=\"NAARKPS\">사천</option>\r\n");
      out.write("\t<option value=\"NAARKPU\">울산</option>\r\n");
      out.write("\t<option value=\"NAARKSI\">인천</option>\r\n");
      out.write("\t<option value=\"NAARKSS\">김포</option>\r\n");
      out.write("\t<option value=\"NAARKTH\">포항</option>\r\n");
      out.write("\t<option value=\"NAARKTN\">대구</option>\r\n");
      out.write("\t<option value=\"NAARKTU\">청주</option>\r\n");
      out.write("</select>\r\n");
      out.write("출발날짜 <input type=\"text\" name=\"depdate\" required> <button>검색</button>\r\n");
      out.write("도착날짜 <input type=\"text\" name=\"depdate2\"> <button>검색</button>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
